$ANSIBLE_VAULT;1.1;AES256
32303530396139316539346130353766663163336161373638323331613135646238663263373135
3734393036313933363233373238336338323339653134390a373164636164383234343634623939
62396338373137643537323636326663356239326538613730666562326561636636626464373536
3462646134643633330a376638393735356361313630623261323434613330346330373335303033
37303336333332653733346438643666656431393663616564626431613162353864633135373861
64306665363736623765663633396335666431373139373838303638636465306566616535376238
39656466393565653833636237303766333336656264323961343132366439633139623862366562
31303862336330643062333934643663366135666339343631373834363263653331626439396262
38346131613164616261336462306537663532633039373861646630346634663266396662636562
30303431313739323833633765353433386137373131313833376131613136363130323430636433
34376532386666316236326639323536323265643833313462666139373738646266323961353935
61333466643630613337
